# Plan: LLM-Powered NPC Companion Game

## Context

You have two completed C++ games (`cpp_shooter_game/`, `cpp_racing_game/`) and an empty `cpp_game_with_llm_npcs/` directory waiting for content. The goal of this third project is a small game where the player can hold a conversation with NPCs whose dialogue is generated by a **single local LLM**, shared across every NPC. Each NPC contributes only a persona prompt and its own short conversation history; the LLM does the talking.

The first milestone is intentionally tiny: a single **companion** NPC you can chat with via a text box. Storyline, world, and other NPC personas come later, once the dialogue loop feels good.

Key constraints from our discussion:
- **Hardware:** 6GB+ NVIDIA VRAM — comfortable up to ~7-8B parameter models at 4-bit quantization.
- **Integration:** Start with **Ollama as a sidecar** (HTTP on localhost), plan a future migration to embedded `llama.cpp` once the design stabilizes.
- **Platform:** **Cross-platform from day one** (Linux + Windows). The existing games are MSYS2/Windows only, so this is a deliberate departure — we'll keep build scripts and paths portable.
- **No new dependencies** in the existing two games. All new deps live under `cpp_game_with_llm_npcs/`.

---

## LLM choice

### Recommended starting model: **Qwen 2.5 3B Instruct** (`qwen2.5:3b-instruct`)
- ~2 GB on disk at Q4_K_M, ~3 GB VRAM at runtime — leaves plenty of headroom.
- Strong instruction-following at small size; good at staying in a persona when given a clear system prompt.
- Fast on a 6GB GPU (30+ tokens/sec typical), so replies feel snappy.
- Permissive license (Apache 2.0–compatible terms for the open weights).

### Honorable mentions (try after Qwen feels limiting)
- **Llama 3.2 3B Instruct** (`llama3.2:3b-instruct`) — comparable size, slightly different writing style. Easy A/B swap.
- **Nous Hermes 3 8B** (`hermes3:8b`) — 8B Llama-3.1 fine-tune explicitly tuned for roleplay and persona consistency. Fits your VRAM at Q4_K_M (~5 GB). This is the upgrade target once you want richer characters.
- **Phi-3.5 Mini 3.8B** (`phi3.5:3.8b-mini-instruct`) — Microsoft's small model; strong reasoning but somewhat stiffer dialogue. Worth trying for contrast.

What we are **not** picking and why:
- Anything under 1B (TinyLlama, SmolLM) — too prone to breaking character mid-reply.
- 13B+ models — overkill for "blacksmith small talk," and slower iteration during development.

### Why a sidecar via Ollama (for now)
- One install (`curl -fsSL https://ollama.com/install.sh | sh` on Linux, installer on Windows) gives you model download, quantization, GPU acceleration, and a stable HTTP API.
- `ollama pull qwen2.5:3b-instruct` is the entire "get the model" step.
- The C++ game just needs an HTTP client — no CMake gymnastics for CUDA/CMake/llama.cpp yet.
- You can swap models with one config line, with no rebuild.
- Migration path to embedded `llama.cpp` later is clean because the `LlmClient` interface will hide the transport.

---

## Architecture

```
┌──────────────────────────────┐         ┌────────────────────────┐
│  cpp_game_with_llm_npcs      │  HTTP   │  Ollama (sidecar)      │
│  (SFML + OpenGL)             │ ──────► │  qwen2.5:3b-instruct   │
│                              │  JSON   │  localhost:11434       │
│  ┌────────────────────────┐  │         └────────────────────────┘
│  │ LlmClient (singleton)  │  │
│  │  - async request queue │  │
│  │  - HTTP via cpp-httplib│  │
│  └─────────▲──────────────┘  │
│            │                 │
│  ┌─────────┴──────────────┐  │
│  │ Npc                    │  │
│  │  - Persona (system     │  │
│  │    prompt template)    │  │
│  │  - ConversationHistory │  │
│  │  - askAsync(playerLine)│  │
│  └─────────▲──────────────┘  │
│            │                 │
│  ┌─────────┴──────────────┐  │
│  │ DialogUI (SFML)        │  │
│  │  - text input          │  │
│  │  - scrolling transcript│  │
│  │  - "thinking..." state │  │
│  └────────────────────────┘  │
└──────────────────────────────┘
```

### Key design points
- **One `LlmClient` for the whole game.** NPCs don't each open their own connection — they all call `LlmClient::chat(personaSystemPrompt, history, userMsg, onReply)`. This matches your "centralized" intent.
- **Async by default.** The game loop never blocks on an LLM call. We use a worker thread + a thread-safe reply queue drained on the main thread (SFML is single-threaded for rendering).
- **Per-NPC history, capped.** Each `Npc` keeps its own conversation as a `vector<Turn>`. We cap it to N most-recent turns (e.g. 10) and prepend the persona system prompt every request. Simple, predictable token usage.
- **Persona template, not hardcoded NPCs.** `Persona { name, role, traits, speakingStyle, knowledgeBoundaries }` rendered into a system prompt string at construction. "Jim the pharmacist" and "Jane the random pedestrian #47" are two `Npc` instances built from the same template — exactly what you described.
- **Streaming optional.** Ollama supports streaming token-by-token; for the first milestone we ignore it and just wait for the full reply (simpler). Add streaming later if reply latency feels long.

---

## New C++ dependencies (only inside `cpp_game_with_llm_npcs/`)

All header-only / vendored to keep cross-platform builds easy. No package manager required.

| Dep | Why | How to add |
| --- | --- | --- |
| **cpp-httplib** | Single-header HTTPS/HTTP client. POST to Ollama. | Vendor `httplib.h` into `external/` |
| **nlohmann/json** | Build/parse Ollama JSON requests and responses. | Vendor `json.hpp` into `external/` |
| **SFML 2.6** | Already used by the other games; reuse for window + text UI. | Same install path as existing games (apt / brew / vcpkg) |

No new runtime libs beyond what SFML already pulls in. Cross-platform "just works" because both vendored libs are header-only.

---

## Proposed directory layout

```
cpp_game_with_llm_npcs/
├── CMakeLists.txt
├── README.md
├── config/
│   └── llm.cfg                 # ollama host, model name, temperature, max tokens
├── external/
│   ├── httplib.h
│   └── json.hpp
├── personas/
│   └── companion.txt           # system prompt template for the first NPC
├── src/
│   ├── main.cpp                # window + game loop + DialogUI glue
│   ├── LlmClient.hpp/.cpp      # HTTP + async queue
│   ├── Npc.hpp/.cpp            # persona + history + askAsync
│   ├── Persona.hpp             # struct + prompt renderer
│   └── DialogUI.hpp/.cpp       # SFML text box + transcript
└── run.sh / run.ps1            # cross-platform launch scripts
```

This mirrors the single-folder-per-game pattern of the other two but adds `src/` subfiles (the other games are single-file; we need more structure here because the LLM glue earns its own modules).

---

## First milestone: "the companion"

A vertical slice you can run end-to-end:

1. **Window** — single SFML window, 1280×720, dark background.
2. **The companion** — one `Npc` loaded from `personas/companion.txt`. Suggested starting persona: a curious traveling companion who knows nothing about real-world topics but lots about the (yet-undefined) game world. Keeps replies short (1-3 sentences).
3. **Dialog UI** — bottom-of-screen text input, scrolling transcript above. Press Enter to send; UI shows "*\<Companion\> is thinking...*" while the LLM call is in flight.
4. **Centralized client** — even with one NPC, the `LlmClient` is built as a singleton from day one so adding NPC #2, #3, etc. requires no refactor.
5. **No game world yet** — no 3D, no movement, no combat. Just the chat. This proves the dialogue loop in isolation before you wire it into anything more ambitious.

---

## Files to create (representative — not exhaustive)

- `cpp_game_with_llm_npcs/CMakeLists.txt` — finds SFML, adds `src/*.cpp`, includes `external/`. Same CMake 3.20+ baseline as your other games.
- `cpp_game_with_llm_npcs/src/LlmClient.hpp/.cpp` — public interface `chat(systemPrompt, history, userMsg, callback)`; internal worker thread and `std::queue<Reply>` drained from main thread.
- `cpp_game_with_llm_npcs/src/Persona.hpp` — struct + `renderSystemPrompt()` that produces the final string Ollama receives.
- `cpp_game_with_llm_npcs/src/Npc.hpp/.cpp` — owns a `Persona` and a bounded `vector<Turn>`; exposes `askAsync(playerLine, onReply)`.
- `cpp_game_with_llm_npcs/src/DialogUI.hpp/.cpp` — SFML text input + transcript rendering + "thinking" indicator.
- `cpp_game_with_llm_npcs/src/main.cpp` — wires it all together; ~150 lines.
- `cpp_game_with_llm_npcs/config/llm.cfg` — key/value (same style as racing game's `track.cfg`): `host=localhost`, `port=11434`, `model=qwen2.5:3b-instruct`, `temperature=0.8`, `max_history_turns=10`.
- `cpp_game_with_llm_npcs/personas/companion.txt` — plain-text system prompt template.
- `cpp_game_with_llm_npcs/run.sh` and `run.ps1` — cross-platform launchers (check Ollama is running, build, run).

---

## Setup steps the user runs once

1. **Install Ollama** — Linux: `curl -fsSL https://ollama.com/install.sh | sh`. Windows: installer from ollama.com.
2. **Pull the model** — `ollama pull qwen2.5:3b-instruct` (~2 GB download).
3. **Confirm it runs** — `ollama run qwen2.5:3b-instruct "say hi"` should reply in a couple of seconds with GPU usage visible in `nvidia-smi`.
4. **Install SFML 2.6** — Linux: `sudo apt install libsfml-dev` (or distro equivalent). Windows: keep the existing MSYS2 path.
5. **Build** — `cmake -S cpp_game_with_llm_npcs -B cpp_game_with_llm_npcs/build && cmake --build cpp_game_with_llm_npcs/build`.
6. **Run** — `./cpp_game_with_llm_npcs/run.sh` (Ollama must be running; the script checks).

---

## Verification (manual test plan for milestone 1)

- `ollama list` shows `qwen2.5:3b-instruct`.
- `curl http://localhost:11434/api/chat -d '{"model":"qwen2.5:3b-instruct","messages":[{"role":"user","content":"hi"}],"stream":false}'` returns a JSON reply with a non-empty `message.content`.
- Game window opens, shows transcript area and input box.
- Typing "hi" and pressing Enter shows the user line in the transcript, then "*Companion is thinking...*", then the reply within a few seconds.
- The reply respects the persona (e.g., refuses to answer real-world questions in character; stays short).
- Sending 15+ messages exercises the history cap — no crash, no slowdown beyond steady state.
- Killing Ollama mid-game produces a graceful in-transcript error like *"\[Companion seems distracted...\]"* rather than a crash.
- Build runs cleanly on at least one Linux box (since cross-platform is a stated goal — if Windows is the only available test target, note that as a follow-up).

---

## Future work (explicitly out of scope for milestone 1)

- **Embed llama.cpp** — once dialogue feels right, swap `LlmClient`'s implementation from cpp-httplib → llama.cpp's C API. The public interface stays the same; only `LlmClient.cpp` changes.
- **Streaming replies** — show tokens as they arrive for a less "frozen" feel.
- **Multiple NPCs in a world** — the architecture already supports this; just instantiate more `Npc`s and add a way to choose who you're talking to (proximity, click, etc.).
- **Persistent memory** — write `vector<Turn>` per NPC to disk between sessions.
- **Game world** — once chat is fun on its own, layer it onto a 3D or 2D world (potentially borrowing rendering patterns from the shooter game).
